apiVersion: v1
kind: Namespace
metadata:
  name: demo-apps
  labels:
    app.kubernetes.io/part-of: observability-demo
    pod-security.kubernetes.io/enforce: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    app.kubernetes.io/part-of: observability-stack
    pod-security.kubernetes.io/enforce: baseline
